//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityBreakout.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int id { get; set; }
        public string firstName { get; set; }
        public Nullable<bool> isForceUser { get; set; }
        public string homePlanet { get; set; }
        public string weapon { get; set; }
        public Nullable<int> kills { get; set; }
    }
}
